### ISSUE TITLE
Swift 3 and Xcode 8 Support

### ISSUE THREAD

**Issue by rahulgautam** [jgretz/Cereal#11]
Please upgrade the library with swift3 

cc @jgretz

**Comment by jgretz** [comment]
Thanks for the issue - I am currently in the process of updating CoreMeta, and then will do this - expect it this week

**Comment by jgretz** [comment]
The code is updated in the repo. I will update the cocoapods as I am able to work through their rc issues

**Comment by jgretz** [comment]
I apologize for the delay in getting back to this. The 2.0.1 version of Cereal is now available as a pod too
